Repository ViniciusResende/AcadGame, pull requests merged in 2022-11, with the labels that each got.

#16 Novas páginas de Fichas de Exercícios e Adição de Exercícios
  .github/pull_request_template.md
  shared/lib/src/AcadGameLib.ts
  shared/lib/src/access/exercise-sheet/ExercisesSheetAccess.ts
  shared/lib/src/access/exercise-sheet/ExercisesSheetErrors.ts
  shared/lib/src/access/exercise-sheet/strategies/ExercisesSheetAccessStrategy.ts
  shared/lib/src/data/enums/ExercisesSheetEnums.ts
  shared/lib/src/data/interfaces/ExercisesSheetInterfaces.ts
  shared/lib/src/engine/exercises-sheet/ExercisesSheetEngine.ts
  shared/lib/src/engine/user/UserEngine.ts
  shared/lib/src/manager/exercise-sheet/ExercisesSheetManager.ts
  shared/lib/src/resource/api/acad/ApiAcad.ts
  shared/lib/src/resource/api/acad/ApiAcadInterfaces.ts
  shared/lib/src/types.ts
  ui/web/src/assets/svg/icons/add-square.svg
  ui/web/src/assets/svg/icons/calendar.svg
  ui/web/src/assets/svg/icons/chevron.svg
  ui/web/src/assets/svg/icons/dumbbell.svg
  ui/web/src/assets/svg/icons/flag.svg
  ui/web/src/assets/svg/icons/index.ts
  ui/web/src/assets/svg/icons/todo-list.svg
  ui/web/src/components/Authenticated/ExercisesAdd/ExercisesAdd.scss
  ui/web/src/components/Authenticated/ExercisesAdd/ExercisesAdd.tsx
  ui/web/src/components/Authenticated/ExercisesAdd/elements/ExerciseAddCard/ExerciseAddCard.scss
  ui/web/src/components/Authenticated/ExercisesAdd/elements/ExerciseAddCard/ExerciseAddCard.tsx
  ui/web/src/components/Authenticated/ExercisesAdd/elements/ExerciseAddCard/index.tsx
  ui/web/src/components/Authenticated/ExercisesAdd/index.tsx
  ui/web/src/components/Authenticated/ExercisesSheets/ExercisesSheets.scss
  ui/web/src/components/Authenticated/ExercisesSheets/ExercisesSheets.tsx
  ui/web/src/components/Authenticated/ExercisesSheets/elements/ExerciseCard/ExerciseCard.scss
  ui/web/src/components/Authenticated/ExercisesSheets/elements/ExerciseCard/ExerciseCard.tsx
  ui/web/src/components/Authenticated/ExercisesSheets/elements/ExerciseCard/index.tsx
  ui/web/src/components/Authenticated/ExercisesSheets/elements/ExerciseUpdateModal/ExerciseUpdateModal.scss
  ui/web/src/components/Authenticated/ExercisesSheets/elements/ExerciseUpdateModal/ExerciseUpdateModal.tsx
  ui/web/src/components/Authenticated/ExercisesSheets/elements/ExerciseUpdateModal/index.tsx
  ui/web/src/components/Authenticated/ExercisesSheets/elements/ExercisesSheet/ExercisesSheet.scss
  ui/web/src/components/Authenticated/ExercisesSheets/elements/ExercisesSheet/ExercisesSheet.tsx
  ui/web/src/components/Authenticated/ExercisesSheets/elements/ExercisesSheet/index.tsx
  ui/web/src/components/Authenticated/ExercisesSheets/index.tsx
  ui/web/src/components/Common/Checkbox/Checkbox.scss
  ui/web/src/components/Common/Checkbox/Checkbox.tsx
  ui/web/src/components/Common/Input/Input.scss
  ui/web/src/components/Common/Input/Input.tsx
  ui/web/src/components/Common/Slider/Slider.scss
  ui/web/src/components/Common/Slider/Slider.tsx
  ui/web/src/components/Common/Slider/index.tsx
  ui/web/src/components/Layout/Authenticated/AutehnticatedLayout.tsx
  ui/web/src/data/enums/ExercisesSheetEnums.ts
  ui/web/src/data/interfaces/ExercisesSheetInterfaces.ts
  ui/web/src/helpers/getCurrentDate.ts
  ui/web/src/helpers/getUniqueId.ts
  ui/web/src/helpers/index.ts
  ui/web/src/hooks/index.ts
  ui/web/src/hooks/useInterval.ts
  ui/web/src/routes/authenticated/RouteExercisesAdd.tsx
  ui/web/src/routes/authenticated/RouteExercisesSheet.tsx
  ui/web/src/routes/authenticated/RouteProfile.tsx
  ui/web/src/routes/authenticated/index.tsx
Labels: enhancement

#17 Implementação de In-App Feedbacks
  shared/lib/src/engine/exercises-sheet/ExercisesSheetEngine.ts
  ui/web/src/assets/svg/icons/xmark.svg
  ui/web/src/components/Authenticated/ExercisesSheets/elements/ExerciseUpdateModal/ExerciseUpdateModal.scss
  ui/web/src/components/Authenticated/ExercisesSheets/elements/ExerciseUpdateModal/ExerciseUpdateModal.tsx
  ui/web/src/components/Authenticated/Profile/Profile.scss
  ui/web/src/components/Common/Input/Input.scss
  ui/web/src/components/Common/Input/Input.tsx
  ui/web/src/components/Common/Slider/Slider.tsx
  ui/web/src/components/Common/Toast/Toast.scss
  ui/web/src/components/Common/Toast/Toast.tsx
  ui/web/src/components/Common/Toast/index.tsx
  ui/web/src/components/Layout/Authenticated/AutehnticatedLayout.tsx
  ui/web/src/components/Layout/Authenticated/elements/Header/Header.tsx
  ui/web/src/components/Layout/Unauthenticated/UnauthenticatedLayout.tsx
  ui/web/src/components/Unauthenticated/Login/Login.tsx
  ui/web/src/components/Unauthenticated/SignUp/SignUp.tsx
  ui/web/src/components/Unauthenticated/utils/index.ts
  ui/web/src/components/Unauthenticated/utils/inputValidation.ts
  ui/web/src/components/Unauthenticated/utils/passwordValidation.ts
  ui/web/src/data/enums/ToastEnums.ts
  ui/web/src/data/types/ToastTypes.ts
  ui/web/src/helpers/dispatchFeedbackToast.ts
  ui/web/src/helpers/index.ts
  ui/web/src/helpers/inputValidators.ts
  ui/web/src/hooks/index.ts
  ui/web/src/hooks/useResize.ts
  ui/web/src/routes/authenticated/RouteExercisesAdd.tsx
  ui/web/src/routes/authenticated/RouteExercisesSheet.tsx
  ui/web/src/routes/authenticated/RouteProfile.tsx
  ui/web/src/routes/unauthenticated/RouteLogin.tsx
  ui/web/src/routes/unauthenticated/RouteSignUp.tsx
  ui/web/src/styles/_variables.scss
Labels: enhancement

#19 Implementações de Responsividade
  ui/web/src/assets/svg/icons/bars.svg
  ui/web/src/assets/svg/icons/chevron-light.svg
  ui/web/src/assets/svg/icons/index.ts
  ui/web/src/components/Authenticated/ExercisesAdd/ExercisesAdd.scss
  ui/web/src/components/Authenticated/ExercisesAdd/ExercisesAdd.tsx
  ui/web/src/components/Authenticated/ExercisesAdd/elements/ExerciseAddCard/ExerciseAddCard.scss
  ui/web/src/components/Authenticated/ExercisesSheets/ExercisesSheets.scss
  ui/web/src/components/Authenticated/ExercisesSheets/elements/ExerciseCard/ExerciseCard.scss
  ui/web/src/components/Authenticated/ExercisesSheets/elements/ExercisesSheet/ExercisesSheet.scss
  ui/web/src/components/Authenticated/Profile/Profile.scss
  ui/web/src/components/Authenticated/Profile/Profile.tsx
  ui/web/src/components/Common/Slider/Slider.scss
  ui/web/src/components/Common/Toast/Toast.tsx
  ui/web/src/components/Layout/Authenticated/elements/Header/Header.scss
  ui/web/src/components/Layout/Authenticated/elements/Header/Header.tsx
  ui/web/src/components/Layout/Authenticated/elements/Header/menuItems.json
Labels: enhancement

#21 Correções de contratos Back<=>Front
  server/adapters/authentication/authRoute.js
  server/adapters/badge/badgeRoute.js
  server/adapters/dayScore/dayScoreRouter.js
  server/adapters/exerciseSheet/exerciseSheetRouter.js
  server/adapters/user/userRoute.js
  server/domains/authentication/authDomain.js
  server/gates/authentication/authExitGate.js
  server/gates/dayScore/dayScoreExitGate.js
  server/gates/exerciseSheet/exerciseSheetExitGate.js
  server/infrastructure/models/exercise.js
  server/middlewares/auth.js
  server/server.js
  shared/lib/src/data/interfaces/ExercisesSheetInterfaces.ts
  shared/lib/src/resource/api/acad/ApiAcad.ts
  shared/lib/src/resource/api/acad/ApiAcadInterfaces.ts
  ui/web/src/components/Authenticated/ExercisesAdd/ExercisesAdd.tsx
  ui/web/src/components/Authenticated/ExercisesAdd/elements/ExerciseAddCard/ExerciseAddCard.tsx
  ui/web/src/components/Authenticated/Profile/elements/WeeklyUserChart/WeeklyUserChartUtils.ts
  ui/web/src/components/Unauthenticated/Login/Login.tsx
  ui/web/src/data/interfaces/ExercisesSheetInterfaces.ts
  ui/web/src/data/interfaces/ProfileInterfaces.ts
  ui/web/src/routes/authenticated/RouteProfile.tsx
  ui/web/src/setup.ts
Labels: bug

#23 Integração de rotas de usuário (+ extras)
  .vscode/launch.json
  AcadGame.code-workspace
  server/README.md
  server/adapters/README.md
  server/adapters/authentication/authAdapter.js
  server/adapters/authentication/authRoute.js
  server/adapters/badge/badgeDBAdapter.js
  server/adapters/badge/badgeRoute.js
  server/adapters/dayScore/dayScoreDBAdapter.js
  server/adapters/dayScore/dayScoreRouter.js
  server/adapters/exerciseSheet/exerciseSheetDBAdapter.js
  server/adapters/exerciseSheet/exerciseSheetRouter.js
  server/adapters/index.js
  server/adapters/user/userDBAdapter.js
  server/adapters/user/userRoute.js
  server/domains/README.md
  server/domains/authentication/authDomain.js
  server/domains/dayScore/dayScoreDomain.js
  server/domains/exerciseSheet/exerciseSheetDomain.js
  server/domains/index.js
  server/domains/user/userDomain.js
  server/gates/README.md
  server/gates/authentication/authExitGate.js
  server/gates/dayScore/dayScoreExitGate.js
  server/gates/exerciseSheet/exerciseSheetExitGate.js
  server/gates/index.js
  server/gates/user/userExitGate.js
  server/infrastructure/README.md
  server/infrastructure/models/exercise.js
  server/infrastructure/models/exerciseSheet.js
  server/infrastructure/models/user.js
  server/package-lock.json
  server/package.json
  server/server.js
  server/utils/authMiddleware.js
  server/utils/errorMiddleware.js
  server/utils/serverErrors.js
  shared/lib/src/resource/api/acad/ApiAcad.ts
  shared/lib/src/resource/api/acad/ApiAcadInterfaces.ts
  shared/lib/src/utils/classes/api-client/ApiClient.ts
  ui/web/src/components/Authenticated/Profile/Profile.tsx
  ui/web/src/components/Common/Slider/Slider.scss
  ui/web/src/data/interfaces/ProfileInterfaces.ts
  ui/web/src/routes/authenticated/RouteExercisesSheet.tsx
  ui/web/src/routes/authenticated/RouteProfile.tsx
Labels: documentation, enhancement

#24 Implementação da Nova página de Ranking
  shared/lib/src/AcadGameLib.ts
  shared/lib/src/access/exercise-sheet/strategies/ExercisesSheetAccessStrategy.ts
  shared/lib/src/access/ranking/RankingAccess.ts
  shared/lib/src/access/ranking/RankingAccessErrors.ts
  shared/lib/src/access/ranking/strategies/RankingAccessStrategy.ts
  shared/lib/src/access/user/strategies/UserAccessStrategyWeeklyHistogram.ts
  shared/lib/src/data/interfaces/RankingInterfaces.ts
  shared/lib/src/engine/ranking/RankingEngine.ts
  shared/lib/src/manager/ranking/RankingManager.ts
  shared/lib/src/resource/api/acad/ApiAcad.ts
  shared/lib/src/resource/api/acad/ApiAcadInterfaces.ts
  ui/web/src/Mappers/UserProfilePictureMappings.ts
  ui/web/src/assets/svg/icons/calendar-star.svg
  ui/web/src/assets/svg/icons/index.ts
  ui/web/src/assets/svg/icons/trophy-star.svg
  ui/web/src/assets/svg/icons/wifi-signal.svg
  ui/web/src/components/Authenticated/Profile/Profile.scss
  ui/web/src/components/Authenticated/Profile/Profile.tsx
  ui/web/src/components/Authenticated/Profile/elements/ProfilePictureEditionModal/ProfilePictureEditionModal.tsx
  ui/web/src/components/Authenticated/Ranking/Ranking.scss
  ui/web/src/components/Authenticated/Ranking/Ranking.tsx
  ui/web/src/components/Authenticated/Ranking/elements/PodiumUser/PodiumUser.scss
  ui/web/src/components/Authenticated/Ranking/elements/PodiumUser/PodiumUser.tsx
  ui/web/src/components/Authenticated/Ranking/elements/PodiumUser/index.tsx
  ui/web/src/components/Authenticated/Ranking/elements/ProfileUser/ProfileUser.scss
  ui/web/src/components/Authenticated/Ranking/elements/ProfileUser/ProfileUser.tsx
  ui/web/src/components/Authenticated/Ranking/elements/ProfileUser/index.tsx
  ui/web/src/components/Authenticated/Ranking/elements/ProfileUserChart/ProfileUserChart.scss
  ui/web/src/components/Authenticated/Ranking/elements/ProfileUserChart/ProfileUserChart.tsx
  ui/web/src/components/Authenticated/Ranking/elements/ProfileUserChart/ProfileUserChartConstants.ts
  ui/web/src/components/Authenticated/Ranking/elements/ProfileUserChart/ProfileUserChartUtils.ts
  ui/web/src/components/Authenticated/Ranking/elements/ProfileUserChart/index.tsx
  ui/web/src/components/Authenticated/Ranking/elements/WeekPodiumChart/WeekPodiumChart.scss
  ui/web/src/components/Authenticated/Ranking/elements/WeekPodiumChart/WeekPodiumChart.tsx
  ui/web/src/components/Authenticated/Ranking/elements/WeekPodiumChart/WeekPodiumChartConstants.ts
  ui/web/src/components/Authenticated/Ranking/elements/WeekPodiumChart/WeekPodiumChartUtils.ts
  ui/web/src/components/Authenticated/Ranking/elements/WeekPodiumChart/index.tsx
  ui/web/src/components/Authenticated/Ranking/elements/WeekRankCard/WeekRankCard.scss
  ui/web/src/components/Authenticated/Ranking/elements/WeekRankCard/WeekRankCard.tsx
  ui/web/src/components/Authenticated/Ranking/elements/WeekRankCard/index.tsx
  ui/web/src/components/Authenticated/Ranking/index.tsx
  ui/web/src/components/Common/Slider/Slider.tsx
  ui/web/src/components/Layout/Authenticated/elements/Header/menuItems.json
  ui/web/src/data/interfaces/RankingInterfaces.ts
  ui/web/src/helpers/chunkArray.ts
  ui/web/src/helpers/cloneObj.ts
  ui/web/src/helpers/index.ts
  ui/web/src/routes/authenticated/RouteExercisesSheet.tsx
  ui/web/src/routes/authenticated/RouteRanking.tsx
  ui/web/src/routes/authenticated/index.tsx
  ui/web/src/routes/unauthenticated/RouteLogin.tsx
  ui/web/src/routes/unauthenticated/RouteSignUp.tsx
  ui/web/src/styles/_variables.scss
Labels: documentation, enhancement

#26 Rotas de amizade (Gym Pals)
  server/adapters/gymPal/gymPalDBAdapter.js
  server/adapters/gymPal/gymPalRouter.js
  server/domains/gymPal/gymPalDomain.js
  server/gates/gymPal/gymPalEntryGate.js
  server/gates/gymPal/gymPalExitGate.js
  server/infrastructure/models/gymPals.js
  server/server.js
Labels: enhancement

#28 Cypress :: Implementação de testes E2E
  cypress.config.ts
  package.json
  tests/cypress/E2E/E2E.cy.ts
  tests/cypress/E2E/E2E.feature
  tests/cypress/fixtures/general/default-error.json
  tests/cypress/fixtures/profile/last-7-days.json
  tests/cypress/fixtures/ranking/week-podium.json
  tests/cypress/integration/execisesSheet/exercisesSheet.cy.ts
  tests/cypress/integration/exercisesSheet.feature
  tests/cypress/integration/header.feature
  tests/cypress/integration/header/header.cy.ts
  tests/cypress/integration/home.feature
  tests/cypress/integration/home/home.cy.ts
  tests/cypress/integration/login.feature
  tests/cypress/integration/login/login.cy.ts
  tests/cypress/integration/profile.feature
  tests/cypress/integration/profile/profile.cy.ts
  tests/cypress/integration/ranking.feature
  tests/cypress/integration/ranking/ranking.cy.ts
  tests/cypress/integration/signUp.feature
  tests/cypress/integration/signUp/signUp.cy.ts
  tests/cypress/plugins/index.js
  tests/cypress/support/commands.ts
  tests/cypress/support/index.ts
  tests/cypress/support/interfaces.ts
  ui/web/src/components/Authenticated/ExercisesSheets/ExercisesSheets.tsx
  ui/web/src/components/Authenticated/ExercisesSheets/elements/ExerciseCard/ExerciseCard.tsx
  ui/web/src/components/Authenticated/Profile/Profile.tsx
  ui/web/src/components/Authenticated/Profile/elements/ProfilePictureEditionModal/ProfilePictureEditionModal.tsx
  ui/web/src/components/Authenticated/Ranking/elements/PodiumUser/PodiumUser.tsx
  ui/web/src/components/Authenticated/Ranking/elements/ProfileUser/ProfileUser.tsx
  ui/web/src/components/Authenticated/Ranking/elements/WeekRankCard/WeekRankCard.tsx
  ui/web/src/data/enums/ToastEnums.ts
  yarn.lock
Labels: documentation, enhancement
